### ISSUE TITLE
[STORM-874] Netty Threads do not handle Errors properly

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#1107]
<p>When low on memory, netty thread could get OOM which if not handled correctly can lead to unexpected behavior such as netty connection leaks.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[?:1.8.0_25]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:1.8.0_25]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_25]
	at org.jboss.netty.buffer.ChannelBuffers.directBuffer(ChannelBuffers.java:167) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.buffer.ChannelBuffers.directBuffer(ChannelBuffers.java:151) ~[netty-3.9.4.Final.jar:?]
	at backtype.storm.messaging.netty.MessageBatch.buffer(MessageBatch.java:101) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at backtype.storm.messaging.netty.MessageEncoder.encode(MessageEncoder.java:32) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.9.4.Final.jar:?]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) ~[netty-3.9.4.Final.jar:?]
	at backtype.storm.messaging.netty.Client.tryDeliverMessages(Client.java:226) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
	at backtype.storm.messaging.netty.Client.send(Client.java:173) ~[storm-core-0.9.2-incubating-security.jar:0.9.2-incubating-security]
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-874" target="_blank">Netty Threads do not handle Errors properly</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kishor Patil" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kishorvpatil">kishorvpatil</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-30T21:00:03+00:00
<li><b>imported</b>: 2025-01-18
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-134759973" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-134759973</a></p>

<p>    @eshioji We are catching `Error` not `RunTimeException` which shows more of a JVM  resource issue - hence we do exit from the JVM - its more serious than just considering some service being down.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user d2r commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#discussion_r43150246" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#discussion_r43150246</a></p>

<p>    &#8212; Diff: storm-core/src/jvm/backtype/storm/messaging/netty/NettyUncaughtExceptionHandler.java &#8212;<br/>
    @@ -0,0 +1,35 @@<br/>
    +/**<br/>
    + * Licensed to the Apache Software Foundation (ASF) under one<br/>
    + * or more contributor license agreements.  See the NOTICE file<br/>
    + * distributed with this work for additional information<br/>
    + * regarding copyright ownership.  The ASF licenses this file<br/>
    + * to you under the Apache License, Version 2.0 (the<br/>
    + * "License"); you may not use this file except in compliance<br/>
    + * with the License.  You may obtain a copy of the License at<br/>
    + *<br/>
    + * <a href="http://www.apache.org/licenses/LICENSE-2.0" class="external-link" target="_blank" rel="nofollow noopener">http://www.apache.org/licenses/LICENSE-2.0</a><br/>
    + *<br/>
    + * Unless required by applicable law or agreed to in writing, software<br/>
    + * distributed under the License is distributed on an "AS IS" BASIS,<br/>
    + * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<br/>
    + * See the License for the specific language governing permissions and<br/>
    + * limitations under the License.<br/>
    + */<br/>
    +package backtype.storm.messaging.netty;<br/>
    +<br/>
    +import backtype.storm.utils.Utils;<br/>
    +import org.slf4j.Logger;<br/>
    +import org.slf4j.LoggerFactory;<br/>
    +<br/>
    +public class NettyUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {<br/>
    +  private static final Logger LOG = LoggerFactory.getLogger(NettyUncaughtExceptionHandler.class);<br/>
    +  @Override<br/>
    +  public void uncaughtException(Thread t, Throwable e) {<br/>
    +    try {<br/>
    +      Utils.handleUncaughtException(e);<br/>
    &#8212; End diff &#8211;</p>

<p>    I agree with @HeartSaVioR , we should at least log any (unchecked) Exception instead of swallow it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kishorvpatil commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/597#issuecomment-160759703" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/597#issuecomment-160759703</a></p>

<p>    These changes went in as part of #838. So closing the PR and JIRA</p>
