### ISSUE TITLE
[STORM-1375] Blobstore broke Pacemaker

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#1603]
<p>When using the new Pacemaker (which, you kind of have to, cos the alternative of not using it is abusing ZK to the point of deadlocking it...), you cannot submit topologies because <em>submitTopology</em> is calling ClusterState's <em>delete_node_blobstore</em> which never got implemented in <em>pacemaker_state_factory.clj</em>.</p>

<p>Here's a nice stack trace:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2015-12-05 07:07:21 b.s.d.nimbus [WARN] Topology submission exception. (topology name='cron-ba161de') #error {
 :cause org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
 :via
 [{:type java.lang.AbstractMethodError
   :message org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
   :at [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]}]
 :trace
 [[sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 497]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [backtype.storm.cluster$mk_storm_cluster_state$reify__3846 setup_blobstore_BANG_ cluster.clj 345]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 497]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [backtype.storm.daemon.nimbus$setup_storm_code invoke nimbus.clj 467]
  [backtype.storm.daemon.nimbus$fn__7774$exec_fn__2579__auto__$reify__7803 submitTopologyWithOpts nimbus.clj 1523]
  [backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts getResult Nimbus.java 2940]
  [backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts getResult Nimbus.java 2924]
  [org.apache.thrift7.ProcessFunction process ProcessFunction.java 39]
  [org.apache.thrift7.TBaseProcessor process TBaseProcessor.java 39]
  [backtype.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor process SimpleTransportPlugin.java 158]
  [org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer invoke AbstractNonblockingServer.java 518]
  [org.apache.thrift7.server.Invocation run Invocation.java 18]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
2015-12-05 07:07:21 o.a.t.s.AbstractNonblockingServer$FrameBuffer [ERROR] Unexpected throwable while invoking!
java.lang.AbstractMethodError: org.apache.storm.pacemaker.pacemaker_state_factory$_mkState$reify__3956.delete_node_blobstore(Ljava/lang/String;Ljava/lang/String;)V
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at backtype.storm.cluster$mk_storm_cluster_state$reify__3846.setup_blobstore_BANG_(cluster.clj:345)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at backtype.storm.daemon.nimbus$setup_storm_code.invoke(nimbus.clj:467)
  at backtype.storm.daemon.nimbus$fn__7774$exec_fn__2579__auto__$reify__7803.submitTopologyWithOpts(nimbus.clj:1523)
  at backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts.getResult(Nimbus.java:2940)
  at backtype.storm.generated.Nimbus$Processor$submitTopologyWithOpts.getResult(Nimbus.java:2924)
  at org.apache.thrift7.ProcessFunction.process(ProcessFunction.java:39)
  at org.apache.thrift7.TBaseProcessor.process(TBaseProcessor.java:39)
  at backtype.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:158)
  at org.apache.thrift7.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518)
  at org.apache.thrift7.server.Invocation.run(Invocation.java:18)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Michael Schonfeld" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=BaconSeason">BaconSeason</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1375" target="_blank">Blobstore broke Pacemaker</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ilya Ostrovskiy" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iostat">iostat</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-12-07T13:56:29+00:00
<li><b>imported</b>: 2025-01-18
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user iostat opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1375" title="Blobstore broke Pacemaker" class="issue-link" data-issue-key="STORM-1375"><del>STORM-1375</del></a> Blobstore broke Pacemaker</p>

<p>    When using the new Pacemaker (which, you kind of have to, cos the alternative of not using it is abusing ZK to the point of deadlocking it...), you cannot submit topologies because submitTopology is calling ClusterState's delete_node_blobstore which never got implemented in pacemaker_state_factory.clj.</p>

<p>    This PR introduces a noop implementation of default-node-blobstore for pacemaker.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/socialrank/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/socialrank/storm</a> pacemaker-blobstore</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/926.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #926</p>

<hr />
<p>commit d14dabdafc9c7c9f5f1b97eae522a0373fe38669<br/>
Author: Ilya Ostrovskiy <ilya@socialrank.com><br/>
Date:   2015-12-05T15:29:36Z</p>

<p>    default noop implementation for delete-node-blobstore for pacemaker_state_factory</p>

<p>commit 2246b72224b418343958f95762ebfdc75c9ab044<br/>
Author: Ilya Ostrovskiy <ilya@socialrank.com><br/>
Date:   2015-12-05T15:32:58Z</p>

<p>    move delete-node-blobstore lower so its not implied it passes through to<br/>
    zk-state</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user redsanket commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162259989" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162259989</a></p>

<p>    +1 NB</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162475213" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162475213</a></p>

<p>    +1 <br/>
    @iostat Could you rebase? 3 commits changes only 1 line.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162525572" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162525572</a></p>

<p>    ugh, seems like github wants to hold on to the previous 3 commits, so now I have 5 commits <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/>. Worth just reopening this PR, or do any of you know a trick for this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162526647" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162526647</a></p>

<p>    @iostat You can rebase your commits into one (squash), and push your working branch to your fork with force option (maybe --force). It will change your PR to one commit.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user schonfeld commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162526706" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162526706</a></p>

<p>    I suppose you could just reset the branch to master, copy/paste the change, and force push to this branch</p>

<p>    > On Dec 7, 2015, at 08:32, Ilya Ostrovskiy <notifications@github.com> wrote:<br/>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162527130" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162527130</a></p>

<p>    alright there we go.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user HeartSaVioR commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162529152" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162529152</a></p>

<p>    Thanks for the update. +1 again.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/926" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user iostat commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/926#issuecomment-162530017" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/926#issuecomment-162530017</a></p>

<p>    Cool. Thanks for the merge!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iostat" class="user-hover" rel="iostat">Ilya Ostrovskiy</a>, I merged into master.</p>
