### ISSUE TITLE
[STORM-1655] Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#1883]
<p>Flux.runCli() swallows any Exceptions when deploying topology remotely, while StormSubmitter.submitTopology() can throw exceptions.<br/>
(AlreadyAliveException, InvalidTopologyException, AuthorizationException, and so on)</p>

<p>It just prints warning log, and return code is 0, not non-zero.</p>

<p>You can easily reproduce via deploying same topology twice with Flux.</p>

---
<details><summary><i>Originally reported by <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-1655" target="_blank">Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jungtaek Lim" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-25T09:10:15+00:00
<li><b>imported</b>: 2025-01-18
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1253" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1253</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a> Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster</p>

<ul>
	<li>Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()</li>
</ul>


<p>    JVM sets exit code to 1 when exception is propagated to main() and even main() doesn't catch it.</p>

<p>    ```<br/>
    ...<br/>
    606  <span class="error">&#91;main&#93;</span> INFO  o.a.s.f.Flux - Running remotely...<br/>
    606  <span class="error">&#91;main&#93;</span> INFO  o.a.s.f.Flux - Deploying topology in an ACTIVE state...<br/>
    619  <span class="error">&#91;main&#93;</span> INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -5653047561138062924:-4997865894002296638<br/>
    669  <span class="error">&#91;main&#93;</span> INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []<br/>
    Exception in thread "main" java.lang.RuntimeException: Topology with name `yaml-topology` already exists on cluster<br/>
    	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:230)<br/>
    	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:288)<br/>
    	at org.apache.storm.flux.Flux.runCli(Flux.java:171)<br/>
    	at org.apache.storm.flux.Flux.main(Flux.java:98)<br/>
     > echo $?<br/>
    1<br/>
    ```</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1253.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1253.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1253</p>

<hr />
<p>commit ba2385882e705ebf5c33f5a03b67dc3b14781460<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-03-24T07:45:24Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a> Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster</p>

<ul>
	<li>Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user HeartSaVioR opened a pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a> (1.x) Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster</p>

<ul>
	<li>Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()</li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/HeartSaVioR/storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/HeartSaVioR/storm</a> <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a>-1.x</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #1254</p>

<hr />
<p>commit 723b08735192895b4a8972c0a8b1a49bb7aae33f<br/>
Author: Jungtaek Lim <kabhwan@gmail.com><br/>
Date:   2016-03-24T07:45:24Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-1655" title="Flux doesn&#39;t set return code to non-zero when there&#39;s any exception while deploying topology to remote cluster" class="issue-link" data-issue-key="STORM-1655"><del>STORM-1655</del></a> Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster</p>

<ul>
	<li>Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()</li>
</ul>


<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user unsleepy22 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254#issuecomment-200819815" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254#issuecomment-200819815</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254#issuecomment-200999571" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254#issuecomment-200999571</a></p>

<p>    +1 </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user knusbaum commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1253#issuecomment-200999693" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1253#issuecomment-200999693</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hustfxj commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254#issuecomment-201091348" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254#issuecomment-201091348</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ptgoetz commented on the pull request:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254#issuecomment-201097134" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254#issuecomment-201097134</a></p>

<p>    +1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1253" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1253</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/storm/pull/1254" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/pull/1254</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Merged into master and 1.x-branch.</p>
