### ISSUE TITLE
[STORM-2847] Exception thrown after rebalance IllegalArgumentException

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#3022]
<p>After rebalance the storm-kafka-client spout attempts to check the current position of partitions that are no longer assigned to the current spout. This occurs in a topology with multiple spout instances.</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:473)</p>

---
<details><summary><i>Originally reported by <a title="Evan Rosebrook" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2847" target="_blank">Exception thrown after rebalance IllegalArgumentException</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-21T17:29:04+00:00
<li><b>imported</b>: 2025-01-18
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Do you have a few more lines of the stack trace? I'm curious if the commit is happening in the rebalance listener.</p>

<p>Also just so I know which version of the code to look at, which commit is your build of 1.2.0 from?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> This is all I have at the moment. If you need more I can get that for you tomorrow. It was on the latest commit as of this morning.</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.emitTupleIfNotEmitted(KafkaSpout.java:328) at org.apache.storm.kafka.spout.KafkaSpout.emit(KafkaSpout.java:309) at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:233) at org.apache.storm.daemon.executor$fn_<em>4976$fn</em><em>4991$fn</em><em>5022.invoke(executor.clj:644) at org.apache.storm.util$async_loop$fn</em>_557.invoke(util.clj:484) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Those line numbers don't match up with the line numbers from 1.x-branch (the 1.2.0 branch). See for example <a href="https://github.com/apache/storm/blob/1.x-branch/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L328" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/1.x-branch/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L328</a> which is supposed to be where emitTupleIfNotEmitted starts according to the stack trace. We haven't merged anything to storm-kafka-client since a few days ago as far as I know. I checked 1.1.x-branch, 1.0.x-branch and master as well (1.0.6, 1.1.2 and 2.0.0 respectively) and the line numbers don't match up to your stack trace either.</p>

<p>I'm assuming the new stack trace is unrelated to the original, since the new trace doesn't contain org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:473)?</p>

<p>It would be good if you could find the commit hash you built from.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p>Apologies <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> , the second stack trace is from a fix I was playing with for the 1.1.x-branch. I am having trouble with rebalance there as well. Ultimately it seemed like I needed some of your recent changes from the 1.x-branch. Here is the rest of the stack trace. Commit 31133fdcecb5e83317729de67ef7ea12a1bd9929</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:473) at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:239) at org.apache.storm.daemon.executor$fn_<em>4976$fn</em><em>4991$fn</em><em>5022.invoke(executor.clj:644) at org.apache.storm.util$async_loop$fn</em>_557.invoke(util.clj:484) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p>the problems persists in 53c2c677e1066df1ac97b7a62a2d41cab484ecbd</p>

<p>java.lang.IllegalArgumentException: You can only check the position for partitions assigned to this consumer. at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1262) at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:475) at org.apache.storm.kafka.spout.KafkaSpout.nextTuple(KafkaSpout.java:239) at org.apache.storm.daemon.executor$fn_<em>4976$fn</em><em>4991$fn</em><em>5022.invoke(executor.clj:644) at org.apache.storm.util$async_loop$fn</em>_557.invoke(util.clj:484) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Thanks. I'll try to figure out why this is happening. In the meantime could you post your KafkaSpout configuration and which Kafka version you're using (broker and client)?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> Here is the requested info:</p>

<p>kafka-clients: 0.10.2.0<br/>
kafka-broker: 0.10.1.0</p>

<p>    val retryService = new KafkaSpoutRetryExponentialBackoff(<br/>
      KafkaSpoutRetryExponentialBackoff.TimeInterval.microSeconds(500),<br/>
      KafkaSpoutRetryExponentialBackoff.TimeInterval.milliSeconds(2),<br/>
      10,<br/>
      KafkaSpoutRetryExponentialBackoff.TimeInterval.seconds(10))</p>

<p>    val recordTranslator = new CustomRecordTranslator(topics, SerializableFactories.getDeserializer)</p>

<p>    new KafkaSpoutConfig.Builder(hosts, classOf<span class="error">&#91;CustomDeserializer&#93;</span>, classOf<span class="error">&#91;CustomDeserializer&#93;</span>, topics)<br/>
      .setGroupId(consumerGroup)<br/>
      .setRetry(retryService)<br/>
      .setRecordTranslator(recordTranslator)<br/>
      .setProp(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, 10000)<br/>
      .setProp(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false")<br/>
      .setProp(ConsumerConfig.RECEIVE_BUFFER_CONFIG, 1048576)<br/>
      .setOffsetCommitPeriodMs(500)<br/>
      .build()</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a>. Your configuration and versions look fine to me.</p>

<p>I've spent some time going over the code, and I'm having a hard time spotting the problem.</p>

<p>The exception you're getting from <a href="https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L475" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L475</a> is saying that the TopicPartition parameter to KafkaConsumer.position was not assigned to the consumer. I don't understand how that can happen, because the TopicPartition parameter is based on the offsetManagers map, and the key set of that map is set to be exactly the partitions that are assigned to the consumer, at <a href="https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L174" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L174</a> and <a href="https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L197" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L197</a>.</p>

<p>Could you try to enable debug logging for the org.apache.storm.kafka.spout log domain and provoking the error again? I particularly want to see if the partitions logged at <a href="https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L164" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L164</a> match the ones logged at <a href="https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L469" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/e2e3f5d19a8671e3759a04b94135fd6643b3aa61/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java#L469</a>.</p>

<p>I'm also curious if the error happens at random, or does it happen at particular moments?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a></p>

<p>It happens at every manually triggered rebalance. It seemed to me like it has to do with partitions being revoked from kafka itself, but the spout still has a reference to them. I'll get you the debug data when I am able.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>When you refer to triggering a rebalance what do you mean? Asking Storm to rebalance the topology or something else?</p>

<p>Also as of 1.2.0 Kafka isn't responsible for managing consumer group partition assignment anymore, the spout handles distributing partitions without consulting Kafka. See <a href="https://issues.apache.org/jira/browse/STORM-2542" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2542</a> for why we made this change. Partition assignment is now handled by <a href="https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscription.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscription.java</a> and associated classes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p>yes, asking storm to rebalance</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I think I have a guess as to what could be wrong. If the spout is deactivated and then reactivated, we replace the KafkaConsumer with a new one. Unfortunately <a href="https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscription.java#L58" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/blob/master/external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscription.java#L58</a> will ensure that we don't assign partitions to the new consumer unless the assignment changes, because we reuse the old ManualPartitionSubscription instance.</p>

<p>I'll look at fixing this in the next few days. Hopefully it's what's causing this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> I believe I have a fix ready for this. Would you be willing to try it out? You can get it from <a href="https://github.com/srdo/storm/tree/STORM-2847-1.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/srdo/storm/tree/STORM-2847-1.x</a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> I Tried your branch and got an error. Apparently the partitions provided to onPartitionsRevoked can be empty. I was able to resolve this by adding " && partitions.size() > 0" to line 152.</p>

<p>Partitions revoked. [consumer-group=MyStormTopology, consumer=org.apache.kafka.clients.consumer.KafkaConsumer@2ada06e4, topic-partitions=[]]<br/>
2017-12-11 15:21:19.908 o.a.s.k.s.KafkaSpout Thread-34-uisspout-executor<span class="error">&#91;703 703&#93;</span> <span class="error">&#91;DEBUG&#93;</span> Offsets successfully committed to Kafka [{uis-12=OffsetAndMetadata{offset=6606783674, metadata='</p>
{topic-partition=uis-12, offset=6606783673, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-28=OffsetAndMetadata{offset=4262625500, metadata='</p>
{topic-partition=uis-28, offset=4262625499, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-44=OffsetAndMetadata{offset=4263152272, metadata='</p>
{topic-partition=uis-44, offset=4263152271, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-60=OffsetAndMetadata{offset=3855749917, metadata='</p>
{topic-partition=uis-60, offset=3855749916, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-76=OffsetAndMetadata{offset=3196437627, metadata='</p>
{topic-partition=uis-76, offset=3196437626, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}, uis-92=OffsetAndMetadata{offset=3209173441, metadata='</p>
{topic-partition=uis-92, offset=3209173440, numFails=0, thread='Thread-34-uisspout-executor[703 703]'}
<p>'}}]<br/>
	at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:467) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.access$400(KafkaSpout.java:59) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout$KafkaSpoutConsumerRebalanceListener.onPartitionsRevoked(KafkaSpout.java:154) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.subscribeKafkaConsumer(KafkaSpout.java:564) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.activate(KafkaSpout.java:555) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.commitOffsetsForAckedTuples(KafkaSpout.java:467) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.access$400(KafkaSpout.java:59) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout$KafkaSpoutConsumerRebalanceListener.onPartitionsRevoked(KafkaSpout.java:154) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.subscribeKafkaConsumer(KafkaSpout.java:564) ~<span class="error">&#91;stormjar.jar:local&#93;</span><br/>
	at org.apache.storm.kafka.spout.KafkaSpout.activate(KafkaSpout.java:555) ~<span class="error">&#91;stormjar.jar:local&#93;</span></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook" class="user-hover" rel="erosebrook">Evan Rosebrook</a> Thanks for testing it. I've updated the branch I linked earlier, please try again if you can. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erosebrook">erosebrook</a>:</i>
<p>Looks good <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a>. I am no longer seeing any exception when manually triggering a rebalance. Nice work!</p>

**Comment by jira-importer** [comment]
<i>[Epic: <a href="https://github.com/apache/infrastructure-jira-issues-import-test/issues?q=in%3Atitle%20STORM-2710%20label%3Aepic">STORM-2710</a>]</i>
