### ISSUE TITLE
[STORM-402] FileNotFoundException when using storm with apache tika

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#637]
<p>I have started using storm with apache tika for text extraction and I encountered a FileNotFoundException emanating from the download-storm-code method in supervisor.clj when running in local mode (I am able to submit to a remote cluster that I created):</p>

<p>7887 <span class="error">&#91;Thread-5&#93;</span> INFO  backtype.storm.daemon.supervisor - Downloading code for storm id LocalTopology-1-1405005513 from /tmp/0de4961a-8694-4646-bb3c-b8e2d49da288/nimbus/stormdist/LocalTopology-1-1405005513<br/>
7906 <span class="error">&#91;Thread-5&#93;</span> INFO  backtype.storm.daemon.supervisor - Copying resources at jar:<a href="file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources</a> to /tmp/61a2365c-f99f-49d6-9bb3-93f84e237fd2/supervisor/stormdist/LocalTopology-1-1405005513/resources<br/>
7907 <span class="error">&#91;Thread-5&#93;</span> ERROR backtype.storm.event - Error when processing event<br/>
java.io.FileNotFoundException: Source 'file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources' does not exist<br/>
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~<span class="error">&#91;commons-io-2.4.jar:2.4&#93;</span><br/>
	at backtype.storm.daemon.supervisor$fn__6392.invoke(supervisor.clj:535) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
	at clojure.lang.MultiFn.invoke(MultiFn.java:236) ~<span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__6286.invoke(supervisor.clj:327) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
	at backtype.storm.event$event_manager$fn__2391.invoke(event.clj:39) ~<span class="error">&#91;storm-core-0.9.3-incubating-SNAPSHOT.jar:0.9.3-incubating-SNAPSHOT&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:24) <span class="error">&#91;clojure-1.5.1.jar:na&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:744) <span class="error">&#91;na:1.7.0_55&#93;</span><br/>
7920 <span class="error">&#91;Thread-5&#93;</span> INFO  backtype.storm.util - Halting process: ("Error when processing an event")</p>

<p>In this case, the download-storm-code method in supervisor.clj is trying to load resources from the URL:</p>

<p>jar:<a href="file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources</a></p>

<p>The relevant code in download-storm-code seems to be:</p>

<p>  (log-message "Copying resources at " (str url) " to " target-dir)<br/>
  (FileUtils/copyDirectory (File. (.getFile url)) (File. target-dir))</p>

<p>Since the url is of the form: <br/>
jar:<a href="file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources</a></p>

<p>the getFile method simply returns:<br/>
<a href="file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources" class="external-link" target="_blank" rel="nofollow noopener">file:/home/milad/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources</a></p>

<p>which is incorrect and leads to the exception.</p>

---
<details><summary><i>Originally reported by <a title="Milad Fatenejad" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=icksa">icksa</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-402" target="_blank">FileNotFoundException when using storm with apache tika</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Milad Fatenejad" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=icksa">icksa</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-07-21T17:48:11+01:00
<li><b>imported</b>: 2025-01-17
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user icksa opened a pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/192" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/192</a></p>

<p>    Fix for <a href="https://issues.apache.org/jira/browse/STORM-402" title="FileNotFoundException when using storm with apache tika" class="issue-link" data-issue-key="STORM-402"><del>STORM-402</del></a>: FileNotFoundException when using storm with apache tika</p>

<p>    This is a fix for <a href="https://issues.apache.org/jira/browse/STORM-402" title="FileNotFoundException when using storm with apache tika" class="issue-link" data-issue-key="STORM-402"><del>STORM-402</del></a>: FileNotFoundException when using storm with apache tika:</p>

<p>    <a href="https://issues.apache.org/jira/browse/STORM-402" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-402</a></p>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/icksa/incubator-storm" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/icksa/incubator-storm</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/192.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/192.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #192</p>

<hr />
<p>commit c2176bafefdc0bcefe2db5586c26d53ff27f0512<br/>
Author: Milad <icksa1@gmail.com><br/>
Date:   2014-07-11T14:01:13Z</p>

<p>    Added a hacky workaround for a FileNotFoundException I encountered<br/>
    while using storm and tika</p>

<p>commit f019eff48b0fbc92b8e147e919dfea910f2b4d19<br/>
Author: Milad <icksa1@gmail.com><br/>
Date:   2014-07-14T12:21:15Z</p>

<p>    Modified resource extraction to use getProtocol</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user revans2 commented on the pull request:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/192#issuecomment-49345959" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/192#issuecomment-49345959</a></p>

<p>    +1, but I want to give others some time to comment too, before I check this in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Thanks Milad,  I merged this into master.  Keep up the good work.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/incubator-storm/pull/192" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/incubator-storm/pull/192</a></p>
